FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# mbgc_loc

Polls is a simple API allowing consumers to view polls and vote in them.

## Manage Location Info [/loc]

### Get all Locations [POST /loc/getAllLocs]

+ Request (application/json)

    + Headers
            
            Cookies: token="abcd"
            
    + Body 
    
            {
                "task_id": 1,
                "pc": 2,
                "pn": 1
            }

+ Response 200 (application/json)

    + Body
    
            {
                "code":200,
                "enmsg":"ok",
                "cnmsg":"成功",
                "data": {
                    "count_page": 1,
                    "count_data": 2,
                    "data": [
                        {
                            "soldier_id":1,
                            "name": "张三",
                            "phone": 13600000000,
                            "serve_office": "海珠人武部",
                            "longitude":111.00,
                            "latitude":111.13
                        },{
                            "soldier_id":2,
                            "name": "李四",
                            "phone": 13600000000,
                            "serve_office": "海珠人武部",
                            "longitude":112.18,
                            "latitude":111.19
                        }
                    ]
                }
            }

### Get Someone Location [POST /loc/getOneLocs]

+ Request (application/json)

    + Headers
            
            Cookies: token="abcd"
            
    + Body 
    
            {
                "task_id": 1,
                "soldier_id": 1,
            }

+ Response 200 (application/json)

    + Body
    
            {
                "code":200,
                "enmsg":"ok",
                "cnmsg":"成功",
                "longitude":112.18,
                "latitude":111.19
            }
            
### Update Someone Location [POST /loc/upOneLocs]

+ Request (application/json)

    + Headers
            
            Cookies: token="abcd"
            
    + Body 
    
            {
                "task_id": 1,
                "soldier_id": 1,
                "longitude": 112.18,
                "latitude": 111.19
            }

+ Response 200 (application/json)

    + Body
    
            {
                "code":200,
                "enmsg":"ok",
                "cnmsg":"成功"
            }